### ISSUE TITLE
[Feature Req] Properly handle duplicate keys when decoding

### ISSUE THREAD

**Issue by nickdnk** [clugg/sm-json#32] opened 2023-03-17 17:41 UTC
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
~Instead of simply returning `null` when an attempt to decode fails, it would be cool if you could pass in a `char[]` which the function would populate with *where* the problem occurred (potentially on which line if it's pretty-printed JSON) and what happened, i.e. `expected }, found ] on line 44`.~

**Describe alternatives you've considered**
n/a

**Additional context**
~Users of get5 will sometimes - for reasons I don't understand, perhaps because they type in JSON manually - make mistakes in their files and not validate them, then ask us/me why their file doesn't load. If this library would tell them what kind of error they have made, it would help with debugging.~

Also, while we're on JSON decoding, `sm-json` gets very confused when it decodes objects with duplicate keys, which is _stupid_, yes, but technically not invalid JSON - the last read key should determine the value of that key, and any others should be ignored/discarded. This caused one consumer of Get5 to have some very strange bugs because sm-json got the object wrong when asked to preserve ordered keys. I would propose it either return `null` *or* handle it correctly in that case.

**Comment by nickdnk** [comment] 2023-03-17 19:14
Never mind, I just found out `json_get_last_error ` already exists.

But the double-key issue still applies.

**Comment by clugg** [comment] 2023-03-25 09:11
Hey mate, thanks for reporting this - I've figured out the root cause for what's going wrong with duplicate keys (ordered keys tracking was incorrectly tracking more than once for keys) & will release a fix as part of v5 (work in progress - will reply to your other issues/PRs with more info). I'll update this issue once a release is out.

**Comment by clugg** [comment] 2023-03-27 13:46
Fixed in [v4.1.3](../releases/tag/v4.1.3), thanks again!

**Closed as completed by clugg** 2023-03-27 13:46 UTC
Labels: enhancement
