### ISSUE TITLE
sourcemod plugin 

### ISSUE THREAD

**Issue by Neptune196** [clugg/sm-json#37] opened 2024-11-11 20:34 UTC
//// sm_translator.sp
//
// C:\Program Files (x86)\steamcmd\l4d2sv\left4dead2\addons\sourcemod\scripting\include\json\helpers\decode.inc(399) : warning 203: symbol is never used: "is_array"
// 399 | int pos,
// --------------------^
// Code size: 69368 bytes
// Data size: 12304 bytes
// Stack/heap size: 18520 bytes
// Total requirements: 100192 bytes
//
// 1 Warning.
//
// Compilation Time: 0.2 sec
// ----------------------------------------

Press enter to exit ...

**Comment by clugg** [comment] 2024-11-14 08:21
Hey @Neptune196,
Thanks for raising this. I am surprised that I've never seen this warning before! This parameter has existed (and been unused) for as long as the function has. Would you mind sharing what version of `spcomp` you're compiling with and any relevant CLI arguments? I made a brief attempt but have been unable to reproduce the warning on my end, and it'd be nice to have warnings like these showing in the pipeline.

Also, I've pushed a fix to [this branch](https://github.com/clugg/sm-json/tree/refs/heads/remove-unused-var) - would you be able to confirm that this solves the warning and everything still works as expected? I'm sure it'll be fine, but I don't have any Source servers on hand to run `json_test` at the moment to confirm.

Thanks again!

**Comment by fbef0102** [comment] 2024-11-16 06:11
The warning because [sourcemod upgrade 1.12 stable](https://www.sourcemod.net/downloads.php?branch=1.12-dev) recently.
Using 1.12 compiler will show the warning.

I can confirme that warning has been fixed

**Comment by clugg** [comment] 2024-11-16 10:54
Thanks @fbef0102, that explains why I've never seen it before! I've added SM 1.12 to the pipeline. The fix has been released in [v5.0.1](../releases/tag/v5.0.1). Thanks again for raising this @Neptune196.

**Closed as completed by clugg** 2024-11-16 10:54 UTC
